spring.application.name=psiquiatra

spring.datasource.url=jdbc:postgresql://localhost:5432/clinica
spring.datasource.username=root
spring.datasource.password=G!tHu825

spring.jpa.hibernate.ddl-auto=update
